baseURL = "/"

enableRobotsTXT = true
disableAliases = true

[params]
disallow_search_engines = false # set robots.txt to disallow everything

# add redirects/headers
[outputs]
home = ["HTML", "RSS", "REDIRECTS", "HEADERS"]

# remove .{ext} from text/netlify
[mediaTypes."text/netlify"]
suffixes = [""]
delimiter = ""

# add output format for netlify _redirects
[outputFormats.REDIRECTS]
mediatype = "text/netlify"
baseName = "_redirects"
isPlainText = true
notAlternative = true

# add output format for netlify _headers
[outputFormats.HEADERS]
mediatype = "text/netlify"
baseName = "_headers"
isPlainText = true
notAlternative = true

[languages]
  [languages.en]
    title = "Selenium HQ"
    weight = 1
    contentDir = "content/en"
    languageName = "English"
    [languages.en.params]
      linkedin = "https://linkedin.com/whoever"
  [languages.fr]
    title = "Selenium QG"
    weight = 2
    contentDir = "content/fr"
    languageName = "Français"
    [languages.fr.params]
      linkedin = "https://linkedin.com/fr/whoever"
      [languages.fr.params.navigation]
        help = "Aide"
  [languages.es]
    title = "Selenium Sede"
    weight = 1
    contentDir = "content/es"
    languageName = "Español"
    [languages.es.params]
      linkedin = "https://linkedin.com/whoever"
  [languages.de]
    title = "Selenium QG"
    weight = 2
    contentDir = "content/de"
    languageName = "Deutsche"
    [languages.de.params]
      linkedin = "https://linkedin.com/fr/whoever"
      [languages.de.params.navigation]
        help = "Aide"
